package lab6;

import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author stefan
 */
public class ConfigPanel extends javax.swing.JPanel {

    final MainFrame frame;
    JLabel label;   //pentru poligoane regulate
    JSpinner sidesField;  // pentru numarul de sides
    JComboBox colorCombo; //culoarea formei

    public ConfigPanel(MainFrame frame) {
        this.frame = frame;
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private void init() {   //am creat labelul cu mesajul respectiv si spinner 
        JLabel sidesLabel = new JLabel("Number of sides:");
        sidesField = new JSpinner(new SpinnerNumberModel(0, 0, 100, 1));
        sidesField.setValue(6); //am setat la un numar de 6 slide uri

        JLabel colorLabel = new JLabel("Colour of label:");
        String[] colors = {"Random", "Balck"};
        colorCombo = new JComboBox(colors);

        //JPanel uses FlowLayout by default
        add(sidesLabel);
        add(sidesField);
        add(colorLabel);
        add(colorCombo);

    }

}
